#=============== consumer  =======================
# 指定默认消费者group id
#spring.kafka.consumer.group-id=test-consumer-group
spring:
  kafka:
    consumer:
      group-id: test-consumer-group-1
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 10001
